# Working with Numbers

This notebook contains tips and tricks of working with vectors and matrices:
* How to generate arrays of numbers
* How to generate, matrices, row- and column-vectors
* How to reotate vectors
* And a first introduction into the often very valuable concept of "broadcasting"

author: Thomas Haslwanter;
date: Nov-2022

## Generating Data

### Generating Evenly Spaced Vectors

In [1]:
# import standard packages
import numpy as np
import matplotlib.pyplot as plt

# To make the display more compact
%precision 3

'%.3f'

In [2]:
# Note that with "arange" the last value is NOT included!
x = np.arange(1, 5, 0.5)
x

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [3]:
# "linspace" produces a given number of linearly spaced numbers
y = np.linspace(0, 1, 11)
y

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Generating Matrices

In [4]:
# Unlike MATLAB, Python by default generates vectors, NOT matrices!
zero_vector = np.zeros(3)
zero_vector

array([0., 0., 0.])

In [5]:
# "np.zeros" and "np.ones" generate zeros and ones, respecitvely.
# They only take ONE input argument, which can be a number or a tuple:
zero_matrix = np.zeros( (3,3))
zero_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# Note: "np.random.randn" in contrast can use more than one input argument:
np.random.randn(3,2)

array([[ 0.069,  0.594],
       [-0.888, -0.86 ],
       [ 0.06 ,  0.448]])

In [7]:
# Here an example of how to conveniently generate a matrix of column vectors:
phi = np.deg2rad(np.arange(0,360,30))
sines = np.sin(phi)
cosines = np.cos(phi)

data_mat = np.column_stack((sines, cosines))

print(np.round(data_mat, 2))


[[ 0.    1.  ]
 [ 0.5   0.87]
 [ 0.87  0.5 ]
 [ 1.    0.  ]
 [ 0.87 -0.5 ]
 [ 0.5  -0.87]
 [ 0.   -1.  ]
 [-0.5  -0.87]
 [-0.87 -0.5 ]
 [-1.   -0.  ]
 [-0.87  0.5 ]
 [-0.5   0.87]]


###  Generate Row- and Column-vectors

In [8]:
# A row-vector can be generated like this ...
row_vector = np.array([1, 2, 3])
row_vector

array([1, 2, 3])

In [9]:
# ... or equivalently like that
row_vector2 = np.r_[3,4,5]
row_vector2

array([3, 4, 5], dtype=int32)

In [10]:
# I know the syntax for generating column-vectors are all a bit weird :(
col_vector = np.c_[[4,5,6]]
col_vector

array([[4],
       [5],
       [6]])

In [11]:
# This one uses the command "np.newaxis" to generate a column vector ....
row_vector[..., np.newaxis]

array([[1],
       [2],
       [3]])

In [12]:
# ... and here is how to use the "reshape" command: the "-1" means "however many there are":
np.reshape(row_vector, (-1,1))

array([[1],
       [2],
       [3]])

#### ATTENTION: Vectors cannot be transposed!!

In [13]:
row_vector

array([1, 2, 3])

In [14]:
# ... is the same as
row_vector.T

array([1, 2, 3])

In [15]:
# If you want to transpose a vector, it has to be 2-dimensional!
vector_2d = np.atleast_2d(row_vector)
vector_2d.T

array([[1],
       [2],
       [3]])

## Working with Vectors and Matrices

### Rotation of a vector

In [16]:
# Rotation matrix for a rotation by 30 deg
alpha = np.deg2rad(30)
rot_mat = np.array([[np.cos(alpha), -np.sin(alpha)],
                    [np.sin(alpha), np.cos(alpha)]])

# The most elegant way to specify a matrix multiplication is with "@"
vec = np.r_[1,0]
vec_rotated = rot_mat @ vec

# Show the results
print(rot_mat)
print('I rotated {0} into {1}'.format(str(vec), str(vec_rotated)))

[[ 0.866 -0.5  ]
 [ 0.5    0.866]]
I rotated [1 0] into [0.866 0.5  ]


### Rotation of a list of vectors

In [17]:
# Lists of vectors, e.g. a sequence of 3D positions, are typically stored as a column-shaped matrix
positions = np.random.randn(10, 2)

# To rotate them, you have to take care that the "positions" match the rotation matrix:
#    they have to be transposed
# And to bring the data back into column shape, you have to transpose them back
rotated = (rot_mat @ positions.T).T

### "Broadcasting"
In *numpy*, "broadcasting" is a convenient way of adding numbers or vectors to a matrix, is the dimensions match up.

Here, I show how to subtract the mean value from each column:

In [18]:
# Generate some data
data = np.arange(15).reshape((5,3))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [19]:
# overall mean
np.mean(data)

7.0

In [20]:
# mean over all rows
np.mean(data, axis=0)

array([6., 7., 8.])

In [21]:
# Now we use "broadcasting" to subtract the mean of each column:
# if the second index matches, the operation is applied to each row:
data - np.mean(data, axis=0)

array([[-6., -6., -6.],
       [-3., -3., -3.],
       [ 0.,  0.,  0.],
       [ 3.,  3.,  3.],
       [ 6.,  6.,  6.]])

**Note:**  This only works on the last index of "data", since the broadcast-rules require that this index matches the first index of the next array!

If this is not the case, an error occurs, as shown by the next statement:

In [22]:
# This only works on the last index of "data";
# since the broadcast-rules require that this index matches 
# with the vector length! 
# WARNING: So the following command will lead to an Error!

# In Python, errors can be caught with "try - except":
try:
    data - np.mean(data, axis=1)
except ValueError:
    print('ERROR: The shape of the operands did not match!')

ERROR: The shape of the operands did not match!
